In [29]:
#numpy assignment-1


import pandas as pd
import numpy as np

In [35]:
#program-1

def vandermonde_function(x):
    y = np.array(x)
    print("matrix output   :",np.vander(y), sep="\n")
    
    
vandermonde_function([1,2,3,4,5])


matrix output   :
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [31]:
#program-2


list=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window_size=3
moving_avg=[]
i=0

while i< (len(list)-window_size+1):
    new_list=list[i:i+window_size]
    avg=sum(new_list)/window_size
    moving_avg.append(avg)
    i=i+1

print("moving_avg output",moving_avg, sep=":  ")

moving_avg output:  [5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
